# routes.yml

portada:
  path: /
  defaults: { _controller: 'Controller\ApplicationController::indexAction' }

section:
  path: /section/
  defaults: { _controller: 'Controller\ApplicationController::indexAction' }