# general configuration
debug: true
base_url: /newLabProy/
enableMarkdown: false # markdown processor

# folders
twigs: /twigs # main twigs folder
sections: /twigs/sections # sections autoloader
log: /log.log # use 'false' to disable logger

# REQUIRED # import as it generates the routing system -> template at
routing:
  url: routes.csv
  format: csv
  indexColumn: name
  exposeJS: false
  exposeTWIG: true
  initialRoute: home

# other data imports
dataImports:
  songs:
    url: https://docs.google.com/spreadsheets/d/1ZTJOMeTe7gbgK3oq30kNycMwRAGHNpa9vkfiJ4MZmJA/export?gid=0&format=csv
    format: csv
    indexColumn:
    exposeJS: true
    exposeTWIG: true
    preprocess: myDataProcessorSample


# advanced configuration
defaultControler: Controller\ApplicationController::indexAction