# general configuration
debug: true
base_url: /newLabProy/

silexUrls:
  twigs: /twigs
  sections: /twigs/sections

defaultRoute: home
enableMarkdown: false

# data imports
dataImports:
      # Required import as it generates the routing system -> template at
  seo:
    url: seo.csv
    format: csv
    indexColumn: name
    exposeJS: false
    exposeTWIG: true
#    preprocess:
  songs:
    url: https://docs.google.com/spreadsheets/d/1ZTJOMeTe7gbgK3oq30kNycMwRAGHNpa9vkfiJ4MZmJA/export?gid=0&format=csv
    format: csv
    indexColumn:
    exposeJS: true
    exposeTWIG: true
#    preprocess: songprocessor


# advanced configuration
defaultControler: Controller\ApplicationController::indexAction