# general configuration
debug: true
base_url: /newLabProy/
enableMarkdown: false           # markdown processor

# folders
twigs: /twigs                   # main twigs folder
sections: /twigs/autoload       # sections autoloader
log: /log.log                   # use 'false' to disable logger

# REQUIRED # import as it generates the routing system and the seo contents
    # the data uses this structure: https://docs.google.com/spreadsheet/ccc?key=0AtJGbTMFIBvQdDJKMzhmMHVZNGRhYmNSc2FyYWZTTlE&usp=sharing
routing:
  url: routes.csv
  format: csv
  indexColumn: name
  exposeJS: false
  exposeTWIG: true
  initialRoute: home

# data imports => use this to use external data files (csv and json) directly into your twig or js
    # url can be a local or external file
dataImports:
  songs:
    url: https://docs.google.com/spreadsheets/d/1ZTJOMeTe7gbgK3oq30kNycMwRAGHNpa9vkfiJ4MZmJA/export?gid=0&format=csv
    format: csv
    indexColumn:
    exposeJS: true
    exposeTWIG: true
    preprocess: myDataProcessorSample


# advanced configuration
defaultControler: Controller\ApplicationController::indexAction